require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false
