require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
